### ISSUE TITLE
Dafda should support multiple consumer instances in asp.net core

### ISSUE THREAD

**Issue by martinosk** [dfds/dafda#10]
Use case:
A message of type "a" may need to be handled by two different consumers "x" and "y".
It should be possible to have different consumer group id's for x and y. The nature of consumer x means a "auto.offset.reset" = "earliest" is required but "y" may require "latest".

To support this, two instances of the Dafda consumer is needed, but the asp.net core configuration extension only works with one instance.

**Comment by jandr-dfds** [comment]
Will be part of v1.0.0 release.
