### ISSUE TITLE
Termination of the current application

### ISSUE THREAD

**Issue by thomasjuul** [dfds/dafda#22]
https://github.com/dfds/dafda/blob/107df94f6cf70385a32e988806c9334c415b9e08/src/Dafda/Consuming/ConsumerHostedService.cs#L45

What is the argument for terminating the entire hosting application?
Why not just throw an exception here?

**Comment by martinosk** [comment]
I believe this is a duplicate of #1
Current error handling in Dafda is extremely basic and relies on you hosting Dafda in a self-repairing environment such as K8s. 
There's room for improvement though.

**Comment by martinosk** [comment]
Duplicate of #1
