### ISSUE TITLE
Envelope parsing fails when a message's property value is not a string

### ISSUE THREAD

**Issue by Cristian-Stanescu** [dfds/dafda#24]
In the JsonIncomingMessageFactory  class the metadataProperties for the message are computed from the JSON string.
JsonElement.GetString() method throws an exception if the value is not a string.
We should perhaps use ToString() instead.

**Comment by cristian-dfds** [comment]
This happens for custom producers that define their own DafdaEnvelope with fields that are not strings

**Comment by ZaradarDFDS** [comment]
In general Dafda should be re-written to enable Interface based message handler registration. As such the class, new generic constraint prevents it, but if your planning to do some work on Dafda maybe you could sort this in the process? :) Ping me if you want some feedback on the issue via slack
