### ISSUE TITLE
Make it possible for others to create branches. So we can contribute with pull requests

### ISSUE THREAD

**Issue by HadiSDev** [dfds/dafda#25]
Make it possible for others to create branches. So we can contribute with pull requests

💯

**Comment by jakob-nielsen-dfds** [comment]
You can fork the repo and make PRs based on this:
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by martinosk** [comment]
> 
> 
> You can fork the repo and make PRs based on this:
> https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

Closing.
