### ISSUE TITLE
Publish a message together with a metadata object 

### ISSUE THREAD

**Issue by nlunn** [dfds/dafda#35]
Whe publishing it would be great if we could use the metadata object when publishing. That would help us ensure that we have set the right keys on the metadata. 

//New overload
_publisher.Publish( MyMessage, MetaData )

**Comment by nlunn** [comment]
There is a mismatch between the Metadata the consumer is using and the dictionary that is being produced by producer.

For the consumer Metadatas internal dictionary is Dictionary<string, string>
For the producer the produced headers is Dictionary<string, object>

This has an impact many places in the code

**Comment by chamook** [comment]
Did your PR resolve this issue, or do you think there are more things that should be changed? :)
