### ISSUE TITLE
Provide an easy way to forward correlationId, causationId and messageId

### ISSUE THREAD

**Issue by nlunn** [dfds/dafda#40]
I would like that it would be easy for the producers to create messages with default Ids, or to forward the ids from messages consumed

When a producer is producing messages without correlation and causation id, they should automatically be set based upon the message id .
```
if
_produce( message );

then
producedMetadata.CorrelationId ==  producedMetadata.MessageId
producedMetadata.CausationId ==  producedMetadata.MessageId
```

When a producer is producing messages and forwarding the MessageHandlerContext provided by the consumer. The new metadata object should have set the following metadata:

```
if
_produce( message, consumedContext );

then
producedMetadata.CorrelationId == consumedContext.CorrelationId
producedMetadata.CausationId == consumedContext.MessageId
```

More about correlation, causation and message id here: 
https://blog.arkency.com/correlation-id-and-causation-id-in-evented-systems/

**Comment by chamook** [comment]
This sounds like a good idea to me.

We should also update [`OutboxEntry`](https://github.com/dfds/dafda/blob/master/src/Dafda/Outbox/OutboxEntry.cs) to include these fields so that we propagate them properly when using an outbox producer :)
